default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gamified_task_manager_api_development

test:
  <<: *default
  database: gamified_task_manager_api_test

production:
  primary: &primary_production
    <<: *default
    database: gamified_task_manager_api_production
    username: gamified_task_manager_api
    password: <%= ENV["GAMIFIED_TASK_MANAGER_API_DATABASE_PASSWORD"] %>
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *default
    database: gamified_task_manager_api_production_queue
    username: gamified_task_manager_api
    password: <%= ENV["GAMIFIED_TASK_MANAGER_API_DATABASE_PASSWORD"] %>
    migrations_paths: db/queue_migrate
    url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_queue" } if ENV["DATABASE_URL"] %>

  cable:
    <<: *primary_production

  cache:
    <<: *primary_production
